package commands

import (
	"errors"
	"fmt"
	"io/ioutil"
	"os"
	"path"
	"strings"
	"unicode"

	"github.com/rigelrozanski/common"
	"github.com/spf13/cobra"
)

func init() {
	RootCmd.AddCommand(CreateAlias)
	RootCmd.AddCommand(UpdateAlias)
}

// keyword for alias gen
const AliasKeyword = "ALIASGEN:"

// CreateAlias creates autogen code for exposed functions
var UpdateAlias = &cobra.Command{
	Use:  "update-alias [alias-file-dir]",
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {

		lines, err := common.ReadLines(args[0])
		if err != nil {
			return err
		}

		srcPrefix := path.Join(os.ExpandEnv("$GOPATH"), "src") + "/"

		var importDirs, fullDirs []string
		for _, line := range lines {
			if strings.Contains(line, AliasKeyword) {
				importDir := strings.TrimSpace(strings.Split(line, AliasKeyword)[1])
				importDirs = append(importDirs, importDir)
				fullDirs = append(fullDirs, path.Join(srcPrefix, importDir))
			}
		}

		thisPath, err := os.Getwd()
		if err != nil {
			return err
		}

		aliasFilePath := path.Join(thisPath, args[0])
		packageName := path.Base(path.Dir(aliasFilePath))
		return CreateAliasFromDirs(packageName, aliasFilePath, importDirs, fullDirs)
	},
}

// CreateAlias creates autogen code for exposed functions
var CreateAlias = &cobra.Command{
	Use:  "create-alias [dirs...]",
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {

		thisPath, err := os.Getwd()
		if err != nil {
			return err
		}
		srcPrefix := path.Join(os.ExpandEnv("$GOPATH"), "src") + "/"
		baseImportDir := strings.TrimPrefix(thisPath, srcPrefix)

		var importDirs, fullDirs []string
		for _, dir := range args {
			importDir := path.Join(baseImportDir, dir) + "/"
			importDirs = append(importDirs, importDir)
			//fullDirs = append(fullDirs, path.Join(thisPath, dir))
			fullDirs = append(fullDirs, path.Join(srcPrefix, importDir))
		}

		packageName := path.Base(thisPath)
		aliasFilePath := path.Join(thisPath, "alias.go")
		return CreateAliasFromDirs(packageName, aliasFilePath, importDirs, fullDirs)
	},
}

// CreateAliasFromDirs
func CreateAliasFromDirs(packageName, aliasFilePath string, importDirs, fullDirs []string) error {
	var pas []PackageAlias
	for i := 0; i < len(importDirs); i++ {
		importDir := importDirs[i]
		fullDir := fullDirs[i]

		files, err := ioutil.ReadDir(fullDir)
		if err != nil {
			return err
		}

		if len(files) == 0 {
			return errors.New("no files")
		}

		pa, err := CreatePackageAlias(importDir, fullDir, files)
		if err != nil {
			return err
		}
		pas = append(pas, pa)
	}

	out := CompileOutput(packageName, pas)
	ioutil.WriteFile(aliasFilePath, []byte(out), 0644)

	command := fmt.Sprintf("go fmt %v", aliasFilePath)
	_, err := common.Execute(command)
	return err
}

// FileAliases - file alaises
type PackageAlias struct {
	Dir        string
	Name       string
	FuncNames  []string
	VarNames   []string
	ConstNames []string
	TypeNames  []string
}

// NewfileAliases creates a new fileAliases object
func CreatePackageAlias(importDir, fullDir string, files []os.FileInfo) (PackageAlias, error) {

	fa := PackageAlias{
		Dir:  importDir,
		Name: path.Base(importDir),
	}
	//localDir := path.Base(importDir) + "/"

	for _, f := range files {
		fname := f.Name()
		if path.Ext(fname) != ".go" || strings.HasSuffix(fname, "_test.go") {
			continue
		}
		filePath := path.Join(fullDir, fname)
		lines, err := common.ReadLines(filePath)
		if err != nil {
			continue
		}

		// get the exported functions
		for _, line := range lines {
			sep := strings.Fields(line)
			if len(sep) > 2 && sep[0] == "func" {
				if sep[1] == "init()" {
					continue
				}
				if unicode.IsLetter(rune(sep[1][0])) && string(sep[1][0]) == strings.ToUpper(string(sep[1][0])) {
					fa.FuncNames = append(fa.FuncNames, strings.Split(sep[1], "(")[0])
				}
			}
		}

		// get the exported constants
		fa.ConstNames = append(fa.ConstNames, getVarOrConstBlocks(lines, "const")...)

		// get the exported variables
		fa.VarNames = append(fa.VarNames, getVarOrConstBlocks(lines, "var")...)

		// get the exported types
		for _, line := range lines {
			sep := strings.Fields(line)
			if len(sep) > 2 &&
				sep[0] == "type" &&
				unicode.IsLetter(rune(sep[1][0])) &&
				string(sep[1][0]) == strings.ToUpper(string(sep[1][0])) {

				fa.TypeNames = append(fa.TypeNames, sep[1])
			}
		}
	}

	return fa, nil
}

// compile package aliases into output string
func CompileOutput(packageName string, pas []PackageAlias) string {

	out := fmt.Sprintf("// nolint")
	out += fmt.Sprintf("\n// autogenerated code using github.com/rigelrozanski/multitool")
	out += fmt.Sprintf("\n// aliases generated for the following subdirectories:")
	for _, alias := range pas {
		out += fmt.Sprintf("\n// %v %v", AliasKeyword, alias.Dir)
	}
	out += fmt.Sprintf("\npackage %s", packageName)

	out += fmt.Sprintf("\n\nimport (")
	for _, alias := range pas {
		out += fmt.Sprintf("\n\t\"%v\"", alias.Dir)
	}
	out += fmt.Sprintf("\n)")

	var constLines, funcLines, varLines, typeLines []string
	for _, pa := range pas {
		for _, constName := range pa.ConstNames {
			constLines = append(constLines, fmt.Sprintf("\n\t%v = %v.%v", constName, pa.Name, constName))
		}
		for _, funcName := range pa.FuncNames {
			funcLines = append(funcLines, fmt.Sprintf("\n\t%v = %v.%v", funcName, pa.Name, funcName))
		}
		for _, varName := range pa.VarNames {
			varLines = append(varLines, fmt.Sprintf("\n\t%v = %v.%v", varName, pa.Name, varName))
		}
		for _, typeName := range pa.TypeNames {
			typeLines = append(typeLines, fmt.Sprintf("\n\t%v = %v.%v", typeName, pa.Name, typeName))
		}
	}

	if len(constLines) > 0 {
		out += fmt.Sprintf("\n\nconst (")
		for _, constLine := range constLines {
			out += constLine
		}
		out += fmt.Sprintf("\n)")
	}

	if len(funcLines)+len(varLines) > 0 {
		out += fmt.Sprintf("\n\nvar (")
		if len(funcLines) > 0 {
			out += fmt.Sprintf("\n\t// functions aliases")
			for _, funcLine := range funcLines {
				out += funcLine
			}
		}

		if len(varLines) > 0 {
			out += fmt.Sprintf("\n\n\t// variable aliases")
			for _, varLine := range varLines {
				out += varLine
			}
		}
		out += fmt.Sprintf("\n)")
	}

	if len(typeLines) > 0 {
		out += fmt.Sprintf("\n\ntype (")
		for _, typeLine := range typeLines {
			out += typeLine
		}
		out += fmt.Sprintf("\n)")
	}
	return out
}

func getVarOrConstBlocks(lines []string, varOrConst string) (names []string) {

	withinBlock := false // within a "var (" or "const (" block

	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, varOrConst+" (") && withinBlock == false:
			withinBlock = true
			continue
		case strings.HasPrefix(line, ")") && withinBlock == true:
			withinBlock = false
			continue

		case withinBlock:
			sep := strings.Fields(line)
			switch {
			case len(sep) < 2:
				continue
			case !unicode.IsLetter(rune(sep[0][0])):
				continue
			default:
				leftOfEq := strings.Split(line, "=")
				lcns := strings.Split(leftOfEq[0], ",")
				for _, lcn := range lcns {
					lcnT := strings.TrimSpace(lcn)
					if fields := strings.Fields(lcn); len(fields) == 0 {
						continue
					}
					lcnT = strings.Fields(lcnT)[0]
					if unicode.IsLetter(rune(lcnT[0])) && string(lcnT[0]) == strings.ToUpper(string(lcnT[0])) {
						names = append(names, lcnT)
					}
				}
			}

		case strings.HasPrefix(line, varOrConst) && withinBlock == false:
			sep := strings.Fields(line)
			switch {
			case len(sep) < 2:
				continue
			case !unicode.IsLetter(rune(sep[1][0])):
				continue
			default:
				afterConst := strings.TrimPrefix(line, varOrConst+" ")
				leftOfEq := strings.Split(afterConst, "=")
				lcns := strings.Split(leftOfEq[0], ",")
				for _, lcn := range lcns {
					lcnT := strings.TrimSpace(lcn)
					if fields := strings.Fields(lcnT); len(fields) == 0 {
						continue
					}
					lcnT = strings.Fields(lcnT)[0]
					if unicode.IsLetter(rune(lcnT[0])) && string(lcnT[0]) == strings.ToUpper(string(lcnT[0])) {
						names = append(names, lcnT)
					}
				}
			}
		}
	}
	return names
}
